### PR TITLE
feat: Add HepMC

### PR DESCRIPTION
**Pull request by mattleblanc**
Hi,

This image is great! 

It would be good to be able to use it with [Rivet](https://rivet.hepforge.org/). The way that I generally do this is by using Pythia's `main42.cc` to generate HepMC events, which go into a fifo that Rivet picks up (a pretty standard way of operating, since LHC HepMC events can be pretty large). I am currently running Rivet using their docker and aliases, as explained on the following page ...

https://gitlab.com/hepcedar/rivet/blob/master/doc/tutorials/docker.md

I guess we would need to add HepMC to the image somehow in order to get `main42.cc` to compile? I'm not sure exactly how you'd like to do that. But in the end I would want to run something that looks like the nasty script below. I think.

:beers: MLB

```
#!/bin/bash
#nasty script for running pythia main42.cc into rivet

cfifo=hepmc.fifo
echo cfifo

filename=out_pythia_into_rivet

echo "./Pythia-Python/tests/main42" "$filename" "$cfifo &"

#./Pythia-Python/tests/main42 "$filename" $cfifo &
docker run --rm -v $PWD:$PWD -w $PWD matthewfeickert/pythia-python:pythia8.301 \
       -c "g++ Pythia-Python/tests/main42.cc -o Pythia-Python/tests/main42  -I$(HEPMC2_INCLUDE) -L$(HEPMC2_LIB) -lpythia8 -lHepMC -ldl; ./Pythia-Python/tests/main42 \
out_pythia_into_rivet $cfifo &"

# 13 TeV JSS from ATLAS
echo "rivet $cfifo -a ATLAS_2019_I1724098:MODE=1  -o " "$(dirname $filename)/Rivet.yoda"  "--analysis-path=/code/LesHouches2019/RivetRoutines/"
rivet $cfifo -a ATLAS_2019_I1724098:MODE=1 -o  "$(dirname $filename)/Rivet.yoda"
```

```
* Add HepMC to image
   - Add HepMC v2.06.10 as HepMC3 is not widely supported currently
* Add HepMC generation using PYTHIA test and add test to CI
* Add hepmc tag to published images
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
Hi @mattleblanc. Thanks for the interest and the PR (I'm going to convert this to a draft for the time being).

So I understand more, you want the [`main42.cc`](https://gitlab.com/Pythia8/releases/-/blob/acc96c3e5332843bce7fa4f4af8d4f8deae0bef3/examples/main42.cc) example form PYTHIA as test case that HepMC is correctly installed, yes? If so that's totally reasonable (though I'm now trying to think if it makes more sense to stream the files from PYTHIA's GitLab project so that they don't need to be here &mdash; probably not though as they are testing files).

> I guess we would need to add HepMC to the image somehow in order to get main42.cc to compile?

We just need to install HepMC during the builder stage. I have a few small tweaks to this image, so you're going to want to rebase this branch soon anyway, but I can either make edits to your branch (as it is a fork of mine) or you can try to add them in. Either way works.

Can you explain what [`main42.cmnd`](https://gitlab.com/Pythia8/releases/-/blob/acc96c3e5332843bce7fa4f4af8d4f8deae0bef3/examples/main42.cmnd) does/how it can be run in the tests? I don't see it being used in the code snippet you put in the PR body.

**Comment by matthewfeickert** [comment]
@mattleblanc from poking around on the `HepMC3` [webpage](http://hepmc.web.cern.ch/hepmc/building.html) and the [GitLab repo](https://gitlab.cern.ch/hepmc/HepMC3) I see that `HepMC` has ROOTIO support. Are you needing this? If so, we should discuss making a new image that is based off of the [ATLAS Stats `atlstats` series of images](https://gitlab.cern.ch/atlas-amglab/atlstats).

**Comment by mattleblanc** [comment]
@matthewfeickert I think that we don't need ROOT (I mean, I like it, but I understand that it is not strictly necessary these days). 

As far as `main42`, the `.cc` & `.cmnd` files I think it is good to directly include here, so that they can be modified. These aren't even the versions of `main42` directly from Pythia, but rather a modified version that includes making an extra PS parameter (`StringPT:sigma`) configurable that we were using at Les Houches last spring. The `cmnd` file is just a config that sets up the usual options at run time (beam type, process, etc.). Running with external cmnd files like this is useful when running tuning scans (and generally is nice). It gets passed to the compiled `.cc` file as an argument, the reason you didn't see it was because I messed up the example above, which should have read something like:

`./main42.exe main42.cmnd hepmcout42.dat > out`

(from the comment at the top of the .cc file)

**Comment by matthewfeickert** [comment]
@mattleblanc I've rebased this PR and added HepMC3 to the Dockerfile. However, when I try to run a local test with the resulting image

```
$ docker run --rm -v $PWD:$PWD -w $PWD matthewfeickert/pythia-python:local-test-latest "g++ tests/main42.cc -o main42 -lpythia8 -lHepMC -ldl"
In file included from tests/main42.cc:18:
/usr/local/include/Pythia8Plugins/HepMC2.h:17:10: fatal error: HepMC/IO_BaseClass.h: No such file or directory
 #include "HepMC/IO_BaseClass.h"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I get the following. Any thoughts here? It seems that your example above is assuming HepMC2(?), but the current releases are HepMC3.

**Comment by matthewfeickert** [comment]
@mattleblanc as you noted from the PYTHIA `README`

```
   HEPMC2) An interface to the HepMC event record, version 2:
       http://lcgapp.cern.ch/project/simu/HepMC/. The interface
       between PYTHIA 8 and HepMC is provided via the
       "include/Pythia8Plugins/HepMC2.h" header.
   HEPMC3) An interface for the upcoming HepMC 3 format. Currently this
       package is not used.
```

while [searching the GitLab source makes it seem like HepMC3 support is there](https://gitlab.com/search?utf8=%E2%9C%93&search=HEPMC3&group_id=&project_id=12340057&search_code=true&repository_ref=master&nav_source=navbar) it probably makes sense to just get HepMC2 installed and running first. That being said, the documentation for HepMC2 is awful or nonexistent (404's on links to docs). From the [HepMC2 GitLab repo](https://gitlab.cern.ch/hepmc/HepMC) it looks like there was CMake support, so if you can find information on those build options that would help.

**Comment by mattleblanc** [comment]
I've got HepMC 2.06.10 building now, untested though

**Comment by matthewfeickert** [comment]
> I've got HepMC 2.06.10 building now, untested though

nice. :+1: I've added some additional CMake flags and changed the install from using Git to just downloading a release tarball as that's faster and there won't be any further releases on HepMC2 (also changed the install target to `/copy/local` to have it get copied over into the final image).

Note that this currently fails tests
```
ctest --verbose --output-on-failure
```
so this needs to get diagnosed and fixed. I'll give it a stab tonight.

**Comment by mattleblanc** [comment]
Cool -- so I have things working now pretty smoothly. I can pass the events generated with `main42` into the Rivet docker image to make some basic plots. There is one problem where Pythia can't find its data files now, which I solve by running `export PYTHIA8DATA=/usr/local\
/share/Pythia8/xmldoc` before I run `main42`. I'm not sure where the best place to fix that is -- I might leave that up to you, @matthewfeickert.

I don't have any additional changes to push here, so let's try to decide what needs to be done to finish this up.

For the record, I am running the following commands to generate events and put them into Rivet ...

```
docker run --rm -v $PWD:$PWD -w $PWD mattleblanc/pythia-python:latest \
       -c "g++ Pythia-Python/tests/main42.cc -o Pythia-Python/tests/main42 -lpythia8 -lHepMC -ldl; export PYTHIA8DATA=/usr/local\
/share/Pythia8/xmldoc; ./Pythia-Python/tests/main42 Pythia-Python/tests/main42.cmnd $cfifo" &

docker run -i  --rm  -u `id -u $USER`:`id -g`  -v $PWD:$PWD -w $PWD  hepstore/rivet:latest rivet $cfifo -a ATLAS_2019_I1724098:MODE=1 -o  "$(dirname $filename)/Rivet.yoda" --ignore-beams
```

... which fills some nice JSS histograms to compare with ATLAS data. Instructions for running Rivet with docker were taken from https://gitlab.com/hepcedar/rivet/blob/master/doc/tutorials/docker.md

:beers: MLB

**Comment by matthewfeickert** [comment]
In light of PR #12, this is the falling build product tree for HepMC:

```
root@87fd992dcce5:/copy/local# tree -L 2
.
├── include
│   └── HepMC
├── lib
│   ├── libHepMC.a
│   ├── libHepMC.so -> libHepMC.so.4
│   ├── libHepMC.so.4 -> libHepMC.so.4.0.0
│   ├── libHepMC.so.4.0.0
│   ├── libHepMCfio.a
│   ├── libHepMCfio.so -> libHepMCfio.so.4
│   ├── libHepMCfio.so.4 -> libHepMCfio.so.4.0.0
│   └── libHepMCfio.so.4.0.0
└── share
    └── HepMC

5 directories, 8 files
```

 so it should be pretty easy to copy only the relevant build files when I patch this.

```docker
COPY --from=builder /usr/local/lib/libHepMC* /usr/local/lib/
COPY --from=builder /usr/local/include/HepMC /usr/local/include/HepMC
COPY --from=builder /usr/local/share/HepMC /usr/local/share/HepMC
```

**Comment by matthewfeickert** [comment]
@mattleblanc Want to give the current state of this repo a try with

```
docker build . -f Dockerfile --tag MLB/pythia-python:debug-latest
```

and then let me know if everything is setup as a user (you) would expect? [The `main42` test is passing](https://github.com/matthewfeickert/Pythia-Python/runs/592891917#step:8:1) but I'm not sure if there are other things you're interested in.

**Comment by mattleblanc** [comment]
No, this is broken again:

```
In file included from Pythia-Python/tests/main42.cc:18:
/usr/local/include/Pythia8Plugins/HepMC2.h:17:10: fatal error: HepMC/IO_BaseClass.h: No such file or directory
 #include "HepMC/IO_BaseClass.h"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by matthewfeickert** [comment]
> No, this is broken again:

Hm. It is [passing CI](https://github.com/matthewfeickert/Pythia-Python/runs/592976667). What commit is at `HEAD` for you? Can you do `git reset --hard origin/HepMC`?

**Comment by mattleblanc** [comment]
It's working! I had done some dangerous git earlier.

From my side, this looks ready to roll.

**Pull request merged**
